### ISSUE TITLE
Dashboard Import fails on filter deletion

### ISSUE THREAD

**Issue by timmcanty** [looker-open-source/gzr#19]
When using dashboard import across two Looker instances, the dashboard import will fail when one of the source filters is deleted.

Repro:
1. In one Looker instance, create a dashboard with 2 filters
2. Use dashboard import to move the dashboard into the second instance
3. In original Looker instance, delete a dashboard filter
4. Attempt to dashboard import. 

Result:
Import fails with `Resource already exists error`

**Comment by deangelo-llooker** [comment]
Looker will sometimes flag something as deleted, but not actually remove it from the database. Let me look into this.

**Comment by cyriel-anthony** [comment]
Hey @deangelo-llooker, have you had a chance to look further into it? Would love some updates on this.

**Comment by jcarah** [comment]
I believe the issue here is that Looker 'soft deletes' dashboards. Try going to Browse > Trash, and delete the old dashboard. This will permanently remove the dashboard. 

I think the issue is that Looker won't let you create a new dashboard with the same slug as another dashboard in a different space. And here,  'different space' is the trash.

@cyriel-anthony @timmcanty wanna give that a shot and let me know if it resolves the issue?

**Comment by deangelo-llooker** [comment]
This has sat for a long time without an update. I believe the issue is resolved. If not please reopen.
