### ISSUE TITLE
Unable to install gazer on mac

### ISSUE THREAD

**Issue by paritoshsingh** [looker-open-source/gzr#41]
➜  ~ gem install gazer
ERROR:  Could not find a valid gem 'looker-sdk-fork' (~> 0.0.6) in any repository
ERROR:  Possible alternatives: looker-sdk

➜  ~ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by asnaseer-resilient** [comment]
I get exactly the same errors on my Mac - Version 10.14.5 (18F203) with the same version of ruby.

**Comment by asnaseer-resilient** [comment]
I had posted this issue here as well: https://discourse.looker.com/t/gazer-a-command-line-tool-for-looker-content-management/8066/7

Izzy responded with the following which fixed my issue:

> I think that error is just a bit confusing, and what it really wants is some kind of looker-sdk.
If you install the “Possible Alternative” with gem install looker-sdk and then install gazer, you should be in business.

**Comment by deangelo-llooker** [comment]
This was part of an older release. You are not getting the latest release of gazer for some reason.

**Comment by deangelo-llooker** [comment]
Try `gem cleanup`, then `gem install gazer`. If that doesn't work, try `gem update gazer`. Finally, you can try to force the version with `gem install gazer -v 0.2.19`.

I'll close this issue, but if that doesn't work please reopen it.
