### ISSUE TITLE
Filters for merged result sets not migrated

### ISSUE THREAD

**Issue by kisa500** [looker-open-source/gzr#69]
What I did: 
I used gzr dashboard cat, followed by gzr dashboard import  --force. 

Issue observed: 
Any merged results that are within the dashboards end up with the filters disabled for them, forcing the need to do a manual edit for each dashboard that was  imported. 

Gzr version: v0.2.40

**Comment by drstrangelooker** [comment]
The quickest way for me to debug these issues is if I can compare the "input" and the "result". So if you can send the file you used as the dashboard import, then do a dashboard cat of the object just imported and send that to me.

If you diff the two files you will see that most of the differences are trivial and can be ignored. For instance the source file has id values from the source system and the result file has different id values. The urls are probably different. You should find a difference in the filter description, however, and you can just send that to me rather than the whole thing.
