### ISSUE TITLE
gzr import seems to be changing the slug value

### ISSUE THREAD

**Issue by twilson650** [looker-open-source/gzr#72]
We are using the slug ID to create persistent URLs across instances. However, since the latest Looker upgrade (and gem update gazer), I found the slug ID in the target system is different than what's in the source JSON. 

The command I'm using is 

gzr dashboard import "source-file.json" 286 --host <host> 

The source-file.json was from a gzr export, and the slug ID matches what is in the source system. However, the target system slug ID is different. This is true if I use --force or if I delete and recreate the dashboard in the target system. 

What might be happening here, and how can I diagnose and fix?

**Comment by megfordpix** [comment]
I'm experiencing this issue as well. I filed a bug against Looker Deployer (here https://github.com/llooker/looker_deployer/issues/39) but I think fixing the issue would require a new feature in Gazer?

**Comment by michaelcramer** [comment]
@twilson650 is this still an issue?

**Comment by ddaugherty** [comment]
Hello @twilson650, @megfordpix 

I have tested this with v0.2.54 and both the slug and ID were preserved with the import.  The import does check for the existence of the same ID / Slug at the target and warns if there is a collision.   

Can you verify if this is still an issue for you with the latest version of Gazer?  Please respond to this comment if you are still experiencing this issue, otherwise this will be closed in ~72 hours. 

Thanks. 
Daniel

**Comment by jannarobertson-bytecode** [comment]
@twilson650 @megfordpix we are closing out this issue; please open another for this or any other issues you're facing, including steps to replicate, Looker, and Gazer versions.  Thank you!
