### ISSUE TITLE
Allow "import" command to pass in a variable instead of file

### ISSUE THREAD

**Issue by daniel-nelson-looker** [looker-open-source/gzr#74]
FR
It would be great if we could do something like

A=`gzr dashboard cat XX --host YY`
gzr dashboard import $A SPACEID --host YY

instead of writing to file.

**Comment by pioneer903** [comment]
+1

**Comment by drstrangelooker** [comment]
Since `gzr dashboard cat` will output to stdout, we can use the standard bash construct to read the output of a command to a environment variable. The combination `$( command )` will read the output of a command. So
```
A="$(gzr dashboard cat XX --host YY)"
```
will do what you want.

Conventionally, using `-` in place of a file name will indicate to read from stdin. I'll add then. Then you would do something like this:
```
A="$(gzr dashboard cat XX --host YY)"
printf '%s\n' "$A" | gzr dashboard import - SPACEID --host YY
```
or alternately
```
A="$(gzr dashboard cat XX --host YY)"
gzr dashboard import - SPACEID --host YY <<< "$A"
```

That will also allow you to implement a HEREDOC like this...
```
gzr dashboard import - SPACEID --host YY << EOF
{
  "id": 123,
  "label": "foo",
   ...
}
EOF
```

This should be easy to do so I'll try to implement it.

So you will be able to embed a literal object in a script as well.

**Comment by michaelcramer** [comment]
Noted enhancement suggestion for potential addition to roadmap.
